FROM registry.cn-hangzhou.aliyuncs.com/cloudnative/python:3.9-slim
WORKDIR /home/admin
COPY . .
RUN /usr/local/bin/python -m pip install --upgrade pip -i https://mirrors.aliyun.com/pypi/simple/ && /usr/local/bin/pip install --no-cache-dir -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/
CMD ["gunicorn", "learning_log.wsgi:application", "-w", "3", "-b", "0.0.0.0:8080"]